# Generated by Django 5.1.5 on 2025-02-16 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=100, unique=True)),
                ('admin_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_name', models.CharField(max_length=100)),
                ('participant_email', models.EmailField(max_length=100, unique=True)),
                ('participant_phone', models.CharField(max_length=20)),
                ('participant_dateOfBirth', models.DateField()),
                ('participant_skills', models.JSONField(default=list)),
                ('participant_linkedin', models.URLField()),
                ('participant_github', models.URLField()),
                ('participant_portfolio', models.URLField(blank=True, null=True)),
                ('participant_haveParticipated', models.BooleanField(blank=True, default=False)),
                ('participant_previousExperience', models.TextField(blank=True, null=True)),
                ('participant_status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_project_name', models.CharField(blank=True, max_length=100, null=True)),
                ('team_project_description', models.TextField(blank=True, max_length=500, null=True)),
                ('team_project_links', models.JSONField(blank=True, default=list, null=True)),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.participant')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.team'),
        ),
    ]
