# Generated by Django 5.1.5 on 2025-02-19 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_admin_is_active_admin_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='admin_id',
            new_name='id',
        ),
    ]
