# Generated by Django 5.1.5 on 2025-02-19 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_admin_email_admin_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='email',
            new_name='admin_email',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='first_name',
            new_name='admin_name',
        ),
        migrations.AddField(
            model_name='admin',
            name='admin_password',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
