# Generated by Django 5.1.5 on 2025-02-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_email_admin_admin_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='password',
        ),
    ]
