# Generated by Django 5.1.5 on 2025-02-19 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_admin_groups_admin_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='admin_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='admin_email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='admin_password',
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
