# Generated by Django 5.1.5 on 2025-02-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_admin_name_admin_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
