# Generated by Django 5.1.5 on 2025-03-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_admin_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_participants', models.IntegerField(default=0)),
                ('total_teams', models.IntegerField(default=0)),
                ('refused_participants', models.IntegerField(default=0)),
                ('accepted_participants', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participant_previousExperience',
        ),
    ]
