# Generated by Django 5.1.5 on 2025-03-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='all_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stat',
            name='all_teams',
            field=models.IntegerField(default=0),
        ),
    ]
